### ISSUE TITLE
MD5 Hash insecure

### ISSUE THREAD

**Issue by bobcom** [lorrx/captcha-generator#2]
Hi lorrex,

How about removing the md5 hashing, ist really insecure.

cya
bobcom

**Comment by lorrx** [comment]
Hi bobcom,

Thank you for your comment.
I know that md5 is deprecated. That's the reason why you can choose between md5, sha1 and crypt. But I will supplement the list of possible encryption types in future.

lorrx

**Comment by bobcom** [comment]
so there is still no reason to implement this method - not all users know that md5 is insecure. Why let them choose?

**Comment by lorrx** [comment]
Dear bobcom
Take a look at the new version (v1.0.1) of the captcha generator. I think that the encryption is more secure now.
Thank you for your request.

Lorrx

**Comment by bobcom** [comment]
Great job lorrx, now it's more secure then ever ;)

thx & bb
